en un proyecto java normal el nuevo codigo agregado en el commit anterior, que usa el mongodb java driver 4.1, funciona perfectamente pero cuando se trabaja en un proyecto modular ocurre este error exception={com.mongodb.MongoException: java.lang.NoClassDefFoundError: jdk/net/ExtendedSocketOptions}.
se debe agregar en el module-info requires jdk.net, que es un modulo usado
por el driver. despues de esto todo funciono perfectamente.